#include "ota_handler.h"
// Generated by web/build-firmware.js
#include "update_page.h"

static bool ota_should_reboot = false;
static unsigned long ota_reboot_at = 0;

static bool ota_authorized = false;

static void ota_handle_page() {
  if (!auth_ok()) return;
  server.sendHeader(F("Content-Encoding"), F("gzip"));
  server.send_P(200, CONTENT_TYPE_HTML, (const char *)UPDATE_PAGE_HTML, UPDATE_PAGE_HTML_LEN);
}

static void ota_handle_upload() {
  HTTPUpload &upload = server.upload();
  uint32_t max_sketch_space;
  User user;

  switch (upload.status) {
    case UPLOAD_FILE_START:
      // Check credentials without answering: writing a response mid-body would
      // corrupt the upload. ota_handle_result sends the 401 afterwards.
      user = auth_load_user();
      ota_authorized = server.authenticate(user.username.c_str(), user.password.c_str());
      if (!ota_authorized) return;

      WiFiUDP::stopAll();
      max_sketch_space = (ESP.getFreeSketchSpace() - 0x1000) & 0xFFFFF000;
      Update.runAsync(true);
      // A failed begin() leaves Update in an error state, which
      // ota_handle_result reports; the writes below are skipped.
      Update.begin(max_sketch_space, U_FLASH);
      break;

    case UPLOAD_FILE_WRITE:
      if (ota_authorized && !Update.hasError()) {
        Update.write(upload.buf, upload.currentSize);
      }
      break;
    case UPLOAD_FILE_END:
      // end(true) fails when fewer bytes arrived than the firmware header
      // announced, which is how a truncated upload is caught.
      if (ota_authorized) {
        Update.end(true);
      }
      break;
    case UPLOAD_FILE_ABORTED:
      if (ota_authorized) {
        Update.end();
      }
  }
  yield();
}

static void ota_handle_result() {
  StreamString err;
  bool authorized;

  // ota_authorized is only set at UPLOAD_FILE_START. Clear it here so a later
  // request that carries no upload body cannot inherit the previous one's
  // authorization.
  authorized = ota_authorized;
  ota_authorized = false;

  if (!authorized) {
    if (!auth_ok()) return;  // sends the 401 challenge
    // Authenticated, but no firmware arrived.
    server.send(400, F("text/plain"), F("No firmware uploaded"));
    return;
  }

  if (Update.hasError()) {
    Update.printError(err);
    server.send(400, F("text/plain"), err);
    return;
  }

  server.sendHeader(F("Connection"), F("close"));
  server.send(200, F("text/plain"), F("OK"));
  ota_should_reboot = true;
  ota_reboot_at = millis() + 1000;
}

// Called from loop()
void ota_loop() {
  if (ota_should_reboot && millis() >= ota_reboot_at) {
    ota_should_reboot = false;
    ESP.restart();
  }
}

void ota_setup_routes() {
  server.on(FPSTR(ROUTE_UPDATE), HTTP_GET, ota_handle_page);
  // The upload handler runs first (per chunk), then the result handler once done.
  server.on(FPSTR(ROUTE_UPDATE), HTTP_POST, ota_handle_result, ota_handle_upload);
}
