// AUTO-GENERATED by web/build-firmware.js - do not edit.
// Source: web/public/portal.css (4724 B -> 3232 B minified).
#ifndef WIFI_PORTAL_STYLE_H
#define WIFI_PORTAL_STYLE_H

static const char PORTAL_STYLE[] PROGMEM =
  "<meta name='viewport' content='width=device-width,initial-scale=1'><meta name='theme-color"
  "' content='#18181b'><style>:root{color-scheme:dark}body{background:#18181b;color:#e4e4e7;f"
  "ont-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;-webkit-font-smoothing:ant"
  "ialiased;padding:1.5rem 1rem}.wrap{max-width:24rem;margin:0 auto;text-align:left}h1{text-a"
  "lign:left;font-weight:600;letter-spacing:-0.02em;color:#e4e4e7;font-size:1.75rem;margin:0 "
  "0 0.25rem}h3{font-size:1rem;color:#a1a1aa;margin:0 0 1.5rem;font-weight:400}input{backgrou"
  "nd:#18181b;color:#e4e4e7;border:1px solid #3f3f46;border-radius:0.5rem;padding:0.5rem 0.75"
  "rem;font-size:0.875rem;margin:0.25rem 0 0.75rem}input::placeholder{color:#8b8b93}input:foc"
  "us,button:focus-visible,a:focus-visible{outline:2px solid #e4e4e7;outline-offset:2px;borde"
  "r-color:#a1a1aa}input[type=checkbox]{width:auto;accent-color:#e4e4e7;margin-right:0.35rem}"
  "button,input[type=submit]{background:transparent;color:#e4e4e7;border:1px solid #3f3f46;bo"
  "rder-radius:0.5rem;padding:0.55rem 1rem;font-size:0.875rem;font-weight:500;line-height:1.5"
  ";cursor:pointer}button:hover,input[type=submit]:hover{background:#26262a;border-color:#525"
  "25b}.wrap>form:first-of-type button,button[type=submit],input[type=submit]{background:#e4e"
  "4e7;color:#18181b;border-color:#e4e4e7}.wrap>form:first-of-type button:hover,button[type=s"
  "ubmit]:hover,input[type=submit]:hover{background:#fff;border-color:#fff}button.D,.wrap>for"
  "m:first-of-type button.D{background:transparent;color:#f87171;border-color:#7f1d1d}button."
  "D:hover,.wrap>form:first-of-type button.D:hover{background:#450a0a;border-color:#991b1b;co"
  "lor:#fca5a5}label{font-size:0.8125rem;font-weight:500;color:#a1a1aa}form{margin:0 0 0.5rem"
  "}br{line-height:0}.wrap>div{display:flex;align-items:center;gap:0.5rem;padding:0;margin:0 "
  "0 0.375rem;border:1px solid #2e2e32;border-radius:0.5rem;background:#212124}.wrap>div:hove"
  "r{background:#26262a;border-color:#3f3f46}.wrap>div>a{flex:1;min-width:0;overflow:hidden;t"
  "ext-overflow:ellipsis;white-space:nowrap;color:#e4e4e7;font-weight:400;text-decoration:non"
  "e;padding:0.6rem 0.75rem}.wrap>div>a:hover{color:#fff;text-decoration:none}a{color:#e4e4e7"
  "}.q{float:none;width:auto;height:auto;min-width:0;padding:0 0.75rem 0 0;color:#8b8b93;font"
  "-size:0.75rem;font-variant-numeric:tabular-nums;margin:0}.msg{display:block;background:#21"
  "2124;color:#e4e4e7;border:1px solid #2e2e32;border-left-width:3px;border-radius:0.5rem;pad"
  "ding:0.875rem;margin:1rem 0;font-size:0.875rem;line-height:1.5}.msg h4{display:block;margi"
  "n:0 0 0.375rem;font-size:0.875rem;font-weight:500}.msg strong{font-weight:500}.msg small,."
  "msg em{color:#a1a1aa;font-style:normal}.msg.P{border-left-color:#a1a1aa}.msg.P h4,.msg.P s"
  "trong{color:#e4e4e7}.msg.D{border-left-color:#f87171}.msg.D h4,.msg.D strong{color:#f87171"
  "}.msg.S{border-left-color:#4ade80}.msg.S h4,.msg.S strong{color:#4ade80}dt{font-weight:500"
  ";color:#e4e4e7;font-size:0.8125rem}dd{color:#a1a1aa;font-size:0.8125rem;margin:0 0 0.5rem}"
  "progress{width:100%;height:0.25rem;border:0;margin-top:0.25rem;background:#2e2e32;-webkit-"
  "appearance:none;appearance:none;border-radius:2px;overflow:hidden}progress::-webkit-progre"
  "ss-bar{background:#2e2e32}progress::-webkit-progress-value{background:#a1a1aa}progress::-m"
  "oz-progress-bar{background:#a1a1aa}.h{display:none}hr{border:0;border-top:1px solid #2e2e3"
  "2;margin:1.25rem 0}</style>";

#endif
