name: Build and Release ESP8266 Firmware

on:
  push:
    tags:
      - 'v*' # "vX.X.X"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Compile Firmware
        run: platformio run

      - name: Prepare Binary
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          BIN_NAME="EspWOL-generic-${TAG_NAME}.bin"
          mkdir -p bin
          rm -f bin/*.bin
          find .pio/build -name "*.bin" -exec mv {} bin/$BIN_NAME \;
        shell: bash

      - name: Commit and Push Binary
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add bin/
          git commit -m "Update firmware binary for ${{ github.ref_name }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp8266-firmware
          path: bin/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Firmware Artifact
        uses: actions/download-artifact@v4
        with:
          name: esp8266-firmware
          path: bin/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*.bin
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: "${{ github.ref_name }}"
          draft: false
          prerelease: false
