name: Build and Release ESP8266 Firmware

on:
  push:
    tags:
      - 'v*' # Runs on tag pushes like vX.X.X

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test Compile for Arduino
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: esp8266:esp8266:generic
          platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          sketch-names: firmware/EspWOL/EspWOL.ino
          
      - name: Prepare Binary
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          BIN_NAME="EspWOL-generic-${TAG_NAME}.bin"
          mkdir -p release-bin
          cp build/esp8266.esp8266.generic/firmware/EspWOL/EspWOL.ino.bin release-bin/$BIN_NAME

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp8266-firmware
          path: release-bin/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Firmware Artifact
        uses: actions/download-artifact@v4
        with:
          name: esp8266-firmware
          path: release-bin/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-bin/*.bin
          tag_name: ${{ github.ref_name }}
          name: "${{ github.ref_name }}"
          draft: false
          prerelease: false