name: Build and Release ESP8266 Firmware

on:
  push:
    tags:
      - 'v*' # Runs on tag pushes like vX.X.X

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2.0.0
        
      - name: Install platform
        run: |
          arduino-cli core update-index --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core install esp8266:esp8266 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json

      - name: Compile ESP8266 Firmware
        run: |
          arduino-cli compile --fqbn esp8266:esp8266:generic firmware/EspWOL/EspWOL.ino --output-dir bin
          
      - name: Prepare Binary
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          BIN_NAME="EspWOL-generic-${TAG_NAME}.bin"
          mv bin/EspWOL.ino.bin bin/$BIN_NAME

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp8266-firmware
          path: bin/*.bin

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Firmware Artifact
        uses: actions/download-artifact@v4
        with:
          name: esp8266-firmware
          path: release-bin/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-bin/*.bin
          tag_name: ${{ github.ref_name }}
          name: "${{ github.ref_name }}"
          draft: false
          prerelease: false