name: Build and Release ESP8266 Firmware

on:
  push:
    tags:
      - 'v*' # Runs on tag pushes like vX.X.X

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266

      - name: Compile ESP8266 Firmware
        run: |
          arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 firmware/EspWOL --output-dir bin
          
      - name: Prepare Binary
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          BIN_NAME="EspWOL-generic-${TAG_NAME}.bin"
          mkdir -p bin
          rm -f bin/*.bin
          mv bin/*.bin bin/$BIN_NAME

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp8266-firmware
          path: bin/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Firmware Artifact
        uses: actions/download-artifact@v4
        with:
          name: esp8266-firmware
          path: bin/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*.bin
          tag_name: ${{ github.ref_name }}
          name: "${{ github.ref_name }}"
          draft: false
          prerelease: false
